/****** Object:  Table [WB].[TBL_GDP]    Script Date: 4/7/2022 9:20:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [WB].[TBL_GDP](
	[PK_ID_GDP] [int] IDENTITY(1,1) NOT NULL,
	[TS_GDP] [datetime2](7) NULL,
	[GDP] [float] NULL,
	[Economy] [nvarchar](100) NULL,
	[Time] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PK_ID_GDP] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


